### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by SanderDeWaal1992** [bevry/sortobject#8]
The provided solution in the readme.md to get the typings to work for TypeScript is not an option for many projects (including ours). I've made a [PR to DefinitelyTyped ](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38840) to add TS typings of sortobject, but they suggested to open an issue in here.

Are you willing to add TypeScript typings to sortobject to help TypeScript users if I do make a PR to this repo (also meaning that these types do need to be updated together with future changes)? Otherwise, are you fine with it if DefinitelyTyped will merge mine PR so that users get the typings from there?

**Comment by andrewbranch** [comment]
When TypeScript 3.7 is released, you’ll be able to generate typings from your existing JSDoc. I added some details here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38840#issuecomment-542878978

**Comment by SanderDeWaal1992** [comment]
TypeScript typings are now added to definitelytyped for as long as the sortobject module does not include TS typings. 

Users can now get the sortobject TypeScript types by installing `@types/sortobject`.
